import { createBoxVariant } from "./createVariants";

// eslint-disable-next-line import/prefer-default-export
export const cardVariants = createBoxVariant({
  kpiPrimary: {
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: "m",
    backgroundColor: "KPICard",
    height: 54,
  },
  kpiHeader: {
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: "m",
    backgroundColor: "KPICard",
    height: 54,
    zIndex: 1,
  },
  kpiSub: {
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: "m",
    backgroundColor: "subKPICard",
    height: 54,
  },
  kpiLastSub: {
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: "m",
    backgroundColor: "subKPICard",
    height: 54,
  },
  pointsBox: {
    height: 54,
    backgroundColor: "pointsBackground",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
  },
  photoCounterBadge: {
    backgroundColor: "photoCounterBadgeBackground",
    justifyContent: "center",
    alignItems: "center",
    height: 32,
    width: 87,
    position: "relative",
    opacity: 0.6,
    borderRadius: 100,
  },
  notification: {
    justifyContent: "center",
    height: 111,
    width: 382,
    borderRadius: 20,
    backgroundColor: "notificationBackground",
  },
  info: {
    height: 86,
    borderRadius: 12,
    borderColor: "infoCardBackground",
    borderWidth: 1,
  },
  space: {
    height: 50,
    borderRadius: 20,
    borderColor: "spaceCardBorder",
    borderWidth: 1,
    backgroundColor: "spaceCardBackground",
  },
  dashed: {
    borderStyle: "dashed",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "dashedCardBorder",
    backgroundColor: "defaultBackground",
    padding: "l",
    justifyContent: "center",
    alignItems: "center",
  },
  file: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "fileCardBorder",
    backgroundColor: "fileCardBackground",
    justifyContent: "space-between",
    alignItems: "center",
  },
  salesNegotiationsIndicator: {
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: "m",
    height: 54,
  },
  salesNegotiation: {
    borderRadius: 10,
    padding: "m",
  },
  salesNegotiationNew: {
    borderRadius: 10,
    padding: "m",
    backgroundColor: "salesNegotiationsCardNewBackground",
  },
  spaceField: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "spaceFieldCardBorder",
    backgroundColor: "defaultBackground",
    padding: "m",
    justifyContent: "center",
    alignItems: "center",
  },
});
